Traceback (most recent call last):
  File "/Users/Xabier/jupyter/lib/python3.7/site-packages/jupyter_cache/executors/utils.py", line 64, in single_nb_execution
    **kwargs,
  File "/Users/Xabier/jupyter/lib/python3.7/site-packages/nbclient/client.py", line 1112, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "/Users/Xabier/jupyter/lib/python3.7/site-packages/nbclient/util.py", line 74, in wrapped
    return just_run(coro(*args, **kwargs))
  File "/Users/Xabier/jupyter/lib/python3.7/site-packages/nbclient/util.py", line 53, in just_run
    return loop.run_until_complete(coro)
  File "/usr/local/opt/python@3.7/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
    return future.result()
  File "/Users/Xabier/jupyter/lib/python3.7/site-packages/nbclient/client.py", line 554, in async_execute
    cell, index, execution_count=self.code_cells_executed + 1
  File "/Users/Xabier/jupyter/lib/python3.7/site-packages/nbclient/client.py", line 857, in async_execute_cell
    self._check_raise_for_error(cell, exec_reply)
  File "/Users/Xabier/jupyter/lib/python3.7/site-packages/nbclient/client.py", line 760, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
gf.line3d   (cx, cy, cz, phirange, newfig = [fig,ax], alpha = 0.4, color = 'black');
------------------

[0;31m---------------------------------------------------------------------------[0m
[0;31mNameError[0m                                 Traceback (most recent call last)
[0;32m<ipython-input-4-f2b26d5c28ee>[0m in [0;36m<module>[0;34m[0m
[0;32m----> 1[0;31m [0mgf[0m[0;34m.[0m[0mline3d[0m   [0;34m([0m[0mcx[0m[0;34m,[0m [0mcy[0m[0;34m,[0m [0mcz[0m[0;34m,[0m [0mphirange[0m[0;34m,[0m [0mnewfig[0m [0;34m=[0m [0;34m[[0m[0mfig[0m[0;34m,[0m[0max[0m[0;34m][0m[0;34m,[0m [0malpha[0m [0;34m=[0m [0;36m0.4[0m[0;34m,[0m [0mcolor[0m [0;34m=[0m [0;34m'black'[0m[0;34m)[0m[0;34m;[0m[0;34m[0m[0;34m[0m[0m
[0m
[0;31mNameError[0m: name 'cx' is not defined
NameError: name 'cx' is not defined

